package pt.upa.utils;

import java.security.PublicKey;
import java.security.cert.Certificate;
import java.security.cert.CertificateFactory;

import static javax.xml.bind.DatatypeConverter.printHexBinary;

import java.io.FileNotFoundException;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.ByteArrayInputStream;
import java.io.File;

import java.math.BigInteger;

public class CertificateReader
{
        private Certificate _certificate;

        /**
         * Read a certificate from a certificate file path of a file generated by 'keytool'.
         * 
         * i.e "keytool -export -keystore "existing_keystore.jks" -alias "keystore_key_alias" -storepass "existing_keystore_password" -file example.cer"
         * 
         */
        public CertificateReader(String path) throws Exception
        {
            _certificate = readCertificate(path);
        }
        
        /**
         * Read a certificate from a certificate file generated by 'keytool'.
         * 
         */
        public CertificateReader(File certificate) throws Exception
        {
            _certificate = readCertificate(certificate);
        }
    
        /**
         * Read a certificate from a byte array.
         * A file can be converted into a byte array (Files.readAllBytes(certificate_file_path)).
         * This is useful because a byte array can be transmitted over the network and then converted back into a Certificate object.
         */
        public CertificateReader(byte[] certificate_bytes) throws Exception
        {
            _certificate = readCertificate(certificate_bytes);
        }
        
        /**
         * Returns the certificates public key encoded as an integer.
         */
        public BigInteger getPublicKeyEncoded() throws Exception
	{   
            PublicKey pkey = _certificate.getPublicKey();
            
            return new BigInteger(printHexBinary(pkey.getEncoded()), 16);
	}
	
	/**
         * Returns the certificates public key.
         */
	public final PublicKey getPublicKey() throws Exception
	{   
            return _certificate.getPublicKey();
        }

        //============= static private ========================================================
        /**
	 * Reads a certificate from a file path.
	 * 
	 * @param certificate_filepath filepath to the certificate
	 * @return Certificate object or null.
	 * @throws Exception
	 */
	 private static Certificate readCertificate(String certificate_filepath) throws Exception
	 {
            BufferedInputStream buffered_instream = null;
            
            Certificate result = null;
            CertificateFactory cert_factory = CertificateFactory.getInstance("X.509");
	 
            try
            {
                buffered_instream = new BufferedInputStream(new FileInputStream(certificate_filepath));
            }
            catch(FileNotFoundException excep)
            {
                excep.printStackTrace();
                System.exit(-1);
            }
            
            int num_bytes_available_to_be_read = buffered_instream.available();
            
            if(num_bytes_available_to_be_read > 0)
            {
                result = cert_factory.generateCertificate(buffered_instream);
            }
            
            buffered_instream.close();
            
            return result;
	 }    
	 
	 
	 /**
	 * Reads a certificate from a byte array.
	 * 
	 * @param certificate_bytes bytes of the certificate
	 * @return Certificate object or null.
	 * @throws Exception
	 */
	 private static Certificate readCertificate(byte[] certificate_bytes) throws Exception
	 {
            BufferedInputStream buffered_instream = null;
            
            Certificate result = null;
            CertificateFactory cert_factory = CertificateFactory.getInstance("X.509");
	 

            buffered_instream = new BufferedInputStream(new ByteArrayInputStream(certificate_bytes));

            
            int num_bytes_available_to_be_read = buffered_instream.available();
            
            if(num_bytes_available_to_be_read > 0)
            {
                result = cert_factory.generateCertificate(buffered_instream);
            }
            
            buffered_instream.close();
            
            return result;
	 }
	 
	 /**
	 * Reads a certificate from a file .
	 * 
	 * @param certificate_file File object of the certificate
	 * @return Certificate object or null.
	 * @throws Exception
	 */
	 private static Certificate readCertificate(File certificate_file) throws Exception
	 {
            BufferedInputStream buffered_instream = null;
            
            Certificate result = null;
            CertificateFactory cert_factory = CertificateFactory.getInstance("X.509");
	 
            try
            {
                buffered_instream = new BufferedInputStream(new FileInputStream(certificate_file));
            }
            catch(FileNotFoundException excep)
            {
                excep.printStackTrace();
                System.exit(-1);
            }
            
            int num_bytes_available_to_be_read = buffered_instream.available();
            
            if(num_bytes_available_to_be_read > 0)
            {
                result = cert_factory.generateCertificate(buffered_instream);
            }
            
            buffered_instream.close();
            
            return result;
	 } 

}